name: "RogueLiteSweeper"
description: created for FlutterCreate
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flare_flutter: 1.3.2
  percent_indicator: 1.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - 'a/f1.flr'
    - 'a/f2.flr'
    - 'a/f3.flr'
    - 'a/f4.flr'
    - 'a/f5.flr'
    - 'a/lv-1.png'
    - 'a/lv-2.png'
    - 'a/lv-3.png'
    - 'a/lv-4.png'
    - 'a/lv-5.png'
    - 'a/0.gif'
    - 'a/2.gif'
    - 'a/4.gif'
    - 'a/8.gif'
    - 'a/16.gif'
    - 'a/32.gif'
    - 'a/64.gif'

  fonts:
    - family: Fnt
      fonts:
        - asset: 'a/pixel.ttf'

  uses-material-design: true
